### ISSUE TITLE
how to find the path of kernel

### ISSUE THREAD

**Issue by 914191848** [WolframResearch/WolframClientForPython#13]
I want to use the wolframclient by my python in anaconda, but raise the error that:

WolframKernelException: Cannot locate a kernel automatically. Please provide an explicit kernel path.

how can i find the path of kernel

**Comment by DbxDev** [comment]
This error comes from the fact that you probably have installed the wolfram kernel in a non-default location. This is perfectly fine, but the library cannot find it automatically, so you need to specify the path manually.
A kernel is a binary called `WolframKernel`.
Using `Mathematica`/`WolframDesktop` or the `Wolfram Engine` evaluate: `First@$CommandLine`. It'll return the path to a Wolfram Kernel. Use this path in Python to initialize instances of `WolframLanguageSession` as explained in the [documentation](https://reference.wolfram.com/language/WolframClientForPython/docpages/basic_usages.html#local-session-initialization).

**Comment by DbxDev** [comment]
Did this answer your question?
