### ISSUE TITLE
How to make a python class automatic conversion in Mathematica

### ISSUE THREAD

**Issue by GalAster** [WolframResearch/WolframClientForPython#15]
I know that class who inherits the `WLSerializable` class and overrides the `to_wl` method can be automatically converted in Mathematica.

But how to modify the existing python class?

For example, how to extend symbols in sympy.

**Comment by DbxDev** [comment]
You should take a look at this section of the documentation:
https://reference.wolfram.com/language/WolframClientForPython/docpages/advanced_usages.html#extending-serialization-writing-an-encoder

It explain how one can define encoders for arbitrary classes.
Please let me know if that answers your question.

**Comment by GalAster** [comment]
Nice work, very easy to use!
