### ISSUE TITLE
Error "No module named 'wolframclient.evaluation'" issued

### ISSUE THREAD

**Issue by monica1131** [WolframResearch/WolframClientForPython#19]
I am trying to do some automation using Mathematica in python. I install the package but I encounter an error "No module named 'wolframclient.evaluation'". I have installed the complete package and there is a folder called evaluation in wolframclient.

**Comment by arnoudbuzing** [comment]
Can you provide the relevant code snippet that reproduces your issue?

**Comment by monica1131** [comment]
I was going through https://reference.wolfram.com/language/WolframClientForPython/ 
when I try to import this command 
>>>from wolframclient.evaluation import WolframLanguageSession

I get the error I have mentioned above.

**Comment by arnoudbuzing** [comment]
Did you run `pip install wolframclient` successfully first?

**Comment by monica1131** [comment]
Yes I did run

**Comment by arnoudbuzing** [comment]
Do you have more than one python installation, where perhaps one works with pip install and the other one does not? Are you perhaps using a very old python version that may not be supported?

**Comment by monica1131** [comment]
I used pip3 install wolframclient

**Comment by arnoudbuzing** [comment]
And what does `python --version` return?

**Comment by monica1131** [comment]
Python 2.7.16

**Comment by arnoudbuzing** [comment]
OK. You need python 3.5 or higher:

![image](https://user-images.githubusercontent.com/3236874/79801235-5caa9a80-8323-11ea-863e-82678308da14.png)

**Comment by monica1131** [comment]
Ok, I agree but I use Anaconda which has python 3.6. I'm working on Jupyter Notebook

**Comment by arnoudbuzing** [comment]
I highly suspect you have multiple python installations (probably more than two?). When you run pip3 it may simply be installing it somewhere where it can not be found (for example by Anaconda). It's a little hard to debug this for me, and also outside of the scope of this repo issue tracker. If you're using a Jupyter notebook, try to check what python installation it is using, and how to install packages for that specific python.

**Comment by riccardodivirgilio** [comment]
Correct, there is something wrong with your env. I suggest to do the following:

1. in your anaconda notebook run:
```
>>> import sys
>>> sys.executable
'/usr/local/opt/python/bin/python3.7'
```
2. use that path to directly run pip install from cli, in order to be extra safe please specify the latest released version explicitly.

```/usr/local/opt/python/bin/python3.7 -m pip install wolframclient==1.1.4```

that should fix your issue, please let me know if this is not helping.

Cheers.

**Comment by monica1131** [comment]
Thank you, the error has been solved. @riccardodivirgilio and @arnoudbuzing
