### ISSUE TITLE
Example to append a path and get a file?

### ISSUE THREAD

**Issue by monica1131** [WolframResearch/WolframClientForPython#20]
Can you provide an example of using WolframClientForPython to append to a path and get a file? I have to file, I know how to work the same in Mathematica it is like 

AppendTo[$Path, "/path”] and  Get["filename"] but with wolframclient I'm not sure.

**Comment by DbxDev** [comment]
This library provide convenient tools to interact with a kernel it has started, (e.g `WolframLanguageSession`). As such anything that works in Mathematica will work the same when done from python (and if it's not the case it's certainly a bug 😉).

The code below update the `$Path` variable and in a second call returns its value:
```
from wolframclient.evaluation import WolframLanguageSession
with WolframLanguageSession() as s:
    s.evaluate('AppendTo[$Path, "some/path"]')
    path = s.evaluate('$Path')
    print(path[-1])
```

**Comment by riccardodivirgilio** [comment]
@monica1131 keep in mind that issues on github are for bug report only. 
Programming questions should be posted on https://mathematica.stackexchange.com/

Thanks.
