### ISSUE TITLE
How to specify the path of kernel

### ISSUE THREAD

**Issue by DeepaMahm** [WolframResearch/WolframClientForPython#25]
Hi All,

I have installed Mathematica in Windows and wolframclient is installed in WSL, Windows Subsystem for Linux.
When I run WolframLanguage Session, the interpreter isn't able to locate the kernel path.

```
    "Cannot locate a kernel automatically. Please provide an explicit kernel path."
wolframclient.exception.WolframKernelException: Cannot locate a kernel automatically. Please provide an explicit kernel path.

```

The documentation available [here](https://reference.wolfram.com/language/WolframClientForPython/docpages/basic_usages.html#local-session-initialization) shows how to set the path.
For instance, on linux
`
session = WolframLanguageSession('/usr/local/Wolfram/Desktop/11.3/Executables/WolframKernel')`

Since I haven't installed Mathematica in WSL, I am not sure how to specify the path.

Any suggestions will be really helpful

**Comment by DeepaMahm** [comment]
This is a kind reminder

**Comment by DbxDev** [comment]
I don't think this question deserve a GitHub ticket. It's rather a question for [Mathematica StackExchange](https://mathematica.stackexchange.com/), possibly a WSL question.
