### ISSUE TITLE
Restarting a session if underlying kernel process is down

### ISSUE THREAD

**Issue by mpeychev** [WolframResearch/WolframClientForPython#30]
Hi,

I was wondering if it is possible to restart a session if the underlying kernel process is down (either killed or if it randomly stops after running for a long time). In such a case, both `session.terminate()` and `session.restart()` hang and seem unable to complete.

Any pointers would be highly appreciated. Thanks.

**Comment by DbxDev** [comment]
This will be fixed in the next library release. Thanks for the report!

**Comment by DbxDev** [comment]
I just pushed a new version which should fix this issue.
