### ISSUE TITLE
How to convert back "WolframObjects" to python objects

### ISSUE THREAD

**Issue by sla-te** [WolframResearch/WolframClientForPython#32]
e.g.
`Table[Values[i], {i, WordData["motorbus", "Synonyms"]}]`
Id like to have a python List..
As of now I am doing it like this (which seems very hacky)
```python
raw_results = evaluate('ExportString[Table[Values[i], {i, WordData["motorbus", "Synonyms"]}], "CSV"]')
result_list = results.replace('"', '').replace('\n', '').split(',')
```

**Comment by riccardodivirgilio** [comment]
Hi, this is documented here:

https://reference.wolfram.com/language/WolframClientForPython/docpages/basic_usages.html#expression-evaluation

by default you are getting back tuples, that are immutable. you can convert them to list with python code.

```
>>> from wolframclient.evaluation import WolframLanguageSession
>>> session = WolframLanguageSession()
>>> res = session.evaluate('Table[Values[i], {i, WordData["motorbus", "Synonyms"]}]')
>>> list(map(list, res))
[['autobus', 'bus', 'charabanc', 'coach', 'double-decker', 'jitney', 'motorcoach', 'omnibus', 'passenger vehicle']]
```
