### ISSUE TITLE
wl.WolframAlpha getting failed in WolframCloudSession

### ISSUE THREAD

**Issue by Deeksha-5** [WolframResearch/WolframClientForPython#35]
I am trying to execute WolframAlpha query through WolframCloudSession, but getting a failed response. Any mistake here?

**MY CODE:**
```
from wolframclient.evaluation import SecuredAuthenticationKey, WolframCloudSession
from wolframclient.language import wl, wlexpr
from PIL import Image

sak = SecuredAuthenticationKey('KEY_1', 'KEY_2')
session = WolframCloudSession(credentials=sak)
session.start()
print(session.authorized())
print(session.evaluate(wl.MinMax([1, 5, -3, 9])))
print(session.evaluate(wl.WolframAlpha("what is the capital of Japan", "Result")))
session.terminate()
```
**OUTPUT:**
True
(-3, 9)
$Failed

**Comment by riccardodivirgilio** [comment]
unfortunately this is not an issue with this library, WolframAlpha doesn't work on the cloud when called using the cloud evaluation api:

```
In[4]:= CloudEvaluate[WolframAlpha["what is the capital of Japan", "Result"]]
Out[4]= $Failed
```

**Comment by riccardodivirgilio** [comment]
Closing the issue, but I will reply with additional informations shortly on what is causing this issue on the cloud api.

Thanks.

**Comment by Deeksha-5** [comment]
Thanks, Please do let me know if some way out is possible.

**Comment by riccardodivirgilio** [comment]
Unfortunatelly this doesn't work with the cloud api for licensing reasons.
