### ISSUE TITLE
The expression Slot[1] cannot be used as a part specification.

### ISSUE THREAD

**Issue by changzeng** [WolframResearch/WolframClientForPython#4]
I'm a new beginner of this framework. When i'm running this command
![image](https://user-images.githubusercontent.com/11350222/53637365-ebf77900-3c5d-11e9-9702-b0af0e38951f.png)
and i got the below error.
![image](https://user-images.githubusercontent.com/11350222/53637400-03cefd00-3c5e-11e9-84de-82b16e4c9fc6.png)
But when i'm running this command directly in mathematica shell. I got the right answer.
![image](https://user-images.githubusercontent.com/11350222/53637462-2cef8d80-3c5e-11e9-9c5d-05044c80be8d.png)

**Comment by DbxDev** [comment]
That's a bug in Mathematica. I reported it. 
Note that the result is correct, even though it not as easy to read because of the Global context.
Thanks.

**Comment by changzeng** [comment]
Ok. Thanks.

**Comment by changzeng** [comment]
I'm using this framework in my project. So I want to know the fix plane of this bug. If there has no extra energy to fix this bug. I would like to contribute.

**Comment by arnoudbuzing** [comment]
@DbxDev If this is a bug in the Wolfram Language itself, we should close the issue here (we should only have open issues here that are fixable here).

**Comment by DbxDev** [comment]
I tend to agree with you but I wasn't sure. I don't want it to look like we're closing unfixed bugs.
For the record this is tracked internally as bug 369081.

**Comment by DbxDev** [comment]
For you information, I've provided a work around to this Wolfram Language bug here: https://github.com/WolframResearch/WolframClientForPython/issues/22#issuecomment-653586842
