### ISSUE TITLE
Example of generating Wolfram Plot in Jupyter Notebook?

### ISSUE THREAD

**Issue by meaningfromdata** [WolframResearch/WolframClientForPython#7]
Can you provide an example of using WolframClientForPython to generate a Mathematica/Wolfram plot from Python that can be displayed inside a Python IDE such as a Jupyter Notebook or Spyder?  I hope this can be done as it would be very useful.

**Comment by riccardodivirgilio** [comment]
There should be examples here:
https://github.com/WolframResearch/WolframLanguageForJupyter

**Comment by DbxDev** [comment]
Here is one way to display images that relies on Wolfram Language `ExportByteArray` and Python `PIL` and `io` modules:

First let's create a basic graphic and store it in `plot`:
```
from wolframclient.evaluation import WolframLanguageSession
from wolframclient.language import wl, wlexpr


session = WolframLanguageSession()
plot = session.evaluate(wlexpr('Plot[Sin[x], {x,0, Pi}]'))
```

Then, convert the Wolfram Language graphic as a PNG image, and export it as a byte array (this is all done by `ExportByteArray`):
```
img_data=session.evaluate(wl.ExportByteArray(plot, 'PNG'))
```

Now import the Python modules that will deal with the raw data:
```
from PIL import Image
import io
```

And import the image:
```
Image.open(io.BytesIO(img_data))
```

This displays an image in a Jupyter notebook.

Don't forget to stop the session:
```
session.stop()
```
